#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Nov 05 23:14:39 EET 2025
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim test_led7_behav -key {Behavioral:sim_1:Functional:test_led7} -tclbatch test_led7.tcl -log simulate.log"
xsim test_led7_behav -key {Behavioral:sim_1:Functional:test_led7} -tclbatch test_led7.tcl -log simulate.log

